eureka:
  instance:
    prefer-ip-address: true 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
      
# JWT
security:
  jwt:
    secret: ${JWT_SECRET:VfhM0XDqDzmobsu90rvnrxTd55Tk5nOA+oyQnTu0AsZBR3PP4tK5kqY12j/GB9HC2jFJQeqjO15sJsqGxAjCSw==}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000