eureka:
  instance:
    prefer-ip-address: true 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
      
# JWT
security:
  jwt:
    secret: ${JWT_SECRET:YlhsemRYQXpjbk16WTNJemRHTXdaRE5tTUhKcWQzUT0=}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000